---
- name: Launch EC2 Instance on california region
  hosts: localhost
  tasks:
  - name:   launching AWS instance using Ansible
    amazon.aws.ec2_instance:
      key_name: califo #Provide the key_name that you have in EC2
      region: us-west-1 #You can enter the region where you want to launch the instance
      instance_type: t2.micro #Enter the instance_type you want launch
      image_id: ami-0cbe318e714fc9a82 #Provide image id
...
