---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Playbook to terminate the ec2 instances
      amazon.aws.ec2_instance:
        state: terminated
        region: us-west-1 #Replace with your region
        filters: 
        instance_ids: #Replace with your instances ids 
          - i-067273be169d7718b
          - i-033f10e9dd120cb36
...
